version: '3'
volumes:
  static_files:
  uploads:
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - docker/prod/.env
  web:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    restart: unless-stopped
    env_file:
      - docker/prod/.env
    command: "python manage.py collectstatic --no-input -v 2 && gunicorn -w 4 main.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_files:/code/static_files
      - uploads:/code/uploads
    depends_on:
      - db
    entrypoint: /entrypoint.sh
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - static_files:/code/static_files
      - uploads:/code/uploads
    depends_on:
      - web